<a href="https://colab.research.google.com/github/NAGPALADITI14/Data_Mining/blob/main/ReadingTextFromDifferentFiles.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# **Reading from a Text file** #

In [ ]:
file1 = open("/content/text.txt","w")
L = ["these lines are written by Aditi Nagpal \n","Thank you everyone \n"]
file1.write("Hello Reader \n")
file1.writelines(L)
file1.close()
# print()

# Open the file in read mode
with open("/content/text.txt", "r") as file:
    content = file.read()
    print(content)

file1 = open("/content/text.txt","r+")
print("Output of Read function is ")
print(file1.read())
print()

file1.seek(0)

print("Output of Readline function is ")
print(file1.readline())
print()

file1.seek(0)

print("Output of Read(9) function is ")
print(file1.read(9))
print()

file1.seek(0)

print("Output of Readline(9) function is ")
print(file1.readline(9))

file1.seek(0)

print("Output of Readlines function is ")
print(file1.readlines())
print()
file1.close()

Hello Reader
these lines are written by Aditi Nagpal
Thank you everyone

Output of Read function is
Hello Reader
these lines are written by Aditi Nagpal
Thank you everyone


Output of Readline function is
Hello Reader


Output of Read(9) function is
Hello Rea

Output of Readline(9) function is
Hello Rea
Output of Readlines function is
['Hello Reader \n', 'these lines are written by Aditi Nagpal \n', 'Thank you everyone \n']

In [ ]:
file1 = open("/content/text.txt","w")

for i in range(4):
  name = input("Enter names of some flowers: ")
  file1.write(name)
  file1.write("\n")

file1.close()
print("Now the contents of file are: \n")

file1 = open("/content/text.txt","r+")
print(file1.read())
print()

Enter names of some flowers: Rose
Enter names of some flowers: Daisy
Enter names of some flowers: Lily
Enter names of some flowers: Sunflower
Now the contents of file are:

Rose
Daisy
Lily
Sunflower

# **Reading Excel and CSV file** #

In [1]:
import pandas as pd

read_csv() function in Pandas is used to read data from CSV files into a Pandas DataFrame.

A DataFrame is a powerful data structure that allows you to manipulate and analyze tabular data efficiently.

CSV files are plain-text files where each row represents a record, and columns are separated by commas (or other delimiters).

In [5]:
df = pd.read_csv("/content/housing.csv")
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0

In [6]:
df1 = pd.read_csv("/content/housing.csv",usecols = ["longitude","latitude","total_rooms"])
print(df1)

       longitude  latitude  total_rooms
0        -122.23     37.88        880.0
1        -122.22     37.86       7099.0
2        -122.24     37.85       1467.0
3        -122.25     37.85       1274.0
4        -122.25     37.85       1627.0
...          ...       ...          ...
20635    -121.09     39.48       1665.0
20636    -121.21     39.49        697.0
20637    -121.22     39.43       2254.0
20638    -121.32     39.43       1860.0
20639    -121.24     39.37       2785.0

[20640 rows x 3 columns]

In [7]:
display(df.head(5))

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0

In [8]:
df.head(5)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0

In [9]:

missing_values = df.isnull()
print(missing_values)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0          False     False               False        False           False
1          False     False               False        False           False
2          False     False               False        False           False
3          False     False               False        False           False
4          False     False               False        False           False
...          ...       ...                 ...          ...             ...
20635      False     False               False        False           False
20636      False     False               False        False           False
20637      False     False               False        False           False
20638      False     False               False        False           False
20639      False     False               False        False           False

       population  households  median_income  median_house_value
0           False       False          False               False
1           False       False          False               False
2           False       False          False               False
3           False       False          False               False
4           False       False          False               False
...           ...         ...            ...                 ...
20635       False       False          False               False
20636       False       False          False               False
20637       False       False          False               False
20638       False       False          False               False
20639       False       False          False               False

[20640 rows x 9 columns]

# **Reading Web-sites** #

In [24]:
import requests
from bs4 import BeautifulSoup

def reading_data():
    url = 'https://www.tableau.com/learn/articles/blogs-about-machine-learning-artificial-intelligence'

    response = requests.get(url)

    if response.status_code == 200:
        print("Website opened successfully\n")

        soup = BeautifulSoup(response.text, 'html.parser')

        section_id_prefix = "paragraph-id--"
        section_index = 195062

        while True:
            section_id = f"{section_id_prefix}{section_index}"
            section = soup.find("section", {"id": section_id})

            if not section:
                break

            heading_tag = section.find("h3")
            if heading_tag:
                print("Heading:", heading_tag.text.strip())

            subheading_tag = section.find("p")
            if subheading_tag:
                print("Content:", subheading_tag.text.strip())

            print("-" * 50)

            section_index += 1
    else:
        print(f"Unable to fetch the webpage. Status code: {response.status_code}")

reading_data()

Website opened successfully

Heading: 1. OpenAI
Content: OpenAI comes from industry experts who want to bring AI to the masses. It's linked to the non-profit research company OpenAI, co-chaired by Elon Musk and Sam Altman, and sponsored by companies such as Amazon Web Services, Microsoft, and Infosys who are trying to make AI accessible—hence the name. Contributors discuss their collective efforts to promote and advance AI technologies through long-term research. It’s a valuable resource for anyone interested in the future of AI.
--------------------------------------------------
Heading: 2. Distill
Content: Managed by: Shan Carter, Chris Olah, and Arvind Satyanarayan
--------------------------------------------------
Heading: 3. Machine Learning is Fun
Content: Authored by: Adam Geitgey
--------------------------------------------------
Heading: 4. Machine Learning Mastery
Content: Authored by: Jason Brownlee
--------------------------------------------------
Heading: 5. The BAIR Blog
Content: Managed by: Berkeley Artificial Intelligence Research
--------------------------------------------------
Heading: 6. FastML
Content: Managed by: Zygmunt Zając
--------------------------------------------------
Heading: 7. AI Trends
Content: Managed by: Cambridge Innovation Institute
--------------------------------------------------
Heading: 10. AI at Google
Content: Related links: Google AI Research Blog and Google AI Technology Blog
--------------------------------------------------
Heading: 9. Apple Machine Learning Journal
Content: Apple’s advancements in voice recognition, predictive text, and autocorrect leveraged for Siri signal some of its machine learning work. And their newest iPhone features ML predominantly in its processor, performing trillions of operations per second; it’s ML in your hands. Apple Machine Learning Journal is a helpful look at how ML shapes their different technologies, and Apple engineers give perspective on how their work influences the transformation of ML.
--------------------------------------------------
Heading: 8. AWS Machine Learning Blog
Content: Amazon is heavily involved in ML, using algorithms in nearly all areas of its business to create leads. Algorithms suggest relevant products for customers in search results, recommend products based on recent purchases, and optimize faster product distribution and shipping from warehouses to customers. The blog features projects and guides that reveal industry strides to readers and covers ML uses in Amazon Web Services technology.
--------------------------------------------------
Content: With greater understanding or appreciation for ML and AI, it’s easier to dispel the myths that may leave doubt about their full potential and to responsibly apply these productive solutions. A Tableau blog post recently explored three common machine learning misconceptions—reviewing them will help you discern fact from fiction in all the industry noise.
--------------------------------------------------

# **Reading a PDF file** #

In [25]:
!pip install pdfplumber -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.5/42.5 kB 2.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.2/48.2 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.5/59.5 kB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 50.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 54.0 MB/s eta 0:00:00

In [39]:
import pdfplumber
pdf = pdfplumber.open("/content/drive/MyDrive/Classroom/BE-CSE-6-S1-Data-Mining-and-Analysis-2025 1/data_mining_practical1.pdf")
pdf.pages

In [38]:
page = pdf.pages[0]
text = page.extract_text()
text

'UNIVERSITY INSTITUTE OF ENGINEERING AND\nTECHNOLOGY (UIET)\nPANJAB UNIVERSITY, CHANDIGARH\nDATA MINING AND ANALYSIS\nCOMPUTER SCIENCE AND ENGINEERING (CSE)\n6TH SEMESTER (2022-2026)\nSubmitted by- Aditi Nagpal\nRoll no-UE223006\nGroup-1\nSection-1\nSubmitted To-Prof. Sarbjeet Singh'

In [37]:
print(text)

UNIVERSITY INSTITUTE OF ENGINEERING AND
TECHNOLOGY (UIET)
PANJAB UNIVERSITY, CHANDIGARH
DATA MINING AND ANALYSIS
COMPUTER SCIENCE AND ENGINEERING (CSE)
6TH SEMESTER (2022-2026)
Submitted by- Aditi Nagpal
Roll no-UE223006
Group-1
Section-1
Submitted To-Prof. Sarbjeet Singh

# **Exception Handling** #

**Error:** Errors are serious issues that a program should not try to handle. They are usually problems in the code’s logic or configuration and need to be fixed by the programmer. Examples include syntax errors and memory errors.

**Exception:** Exceptions are less severe than errors and can be handled by the program. They occur due to situations like invalid input, missing files or network issues.

In [41]:
import logging
logging.basicConfig(filename='app.log', level=logging.DEBUG)


def read_file(file_path):
    try:
        with open(file_path, 'r') as file:
            content = file.read()
        return content
    except FileNotFoundError as e:
        logging.error(f"FileNotFoundError: The file at {file_path} was not found.")
        print(f"Error: The file at {file_path} was not found.")

    except PermissionError as e:
        logging.error(f"PermissionError: No permission to access the file at {file_path}.")
        print(f"Error: No permission to access the file at {file_path}.")

    except Exception as e:
        logging.error(f"An unexpected error occurred: {e}")
        print("An unexpected error occurred.")
    return None


def convert_to_integer(value):
    try:
        return int(value)
    except ValueError as e:
        logging.error(f"ValueError: Unable to convert '{value}' to an integer.")
        print(f"Error: '{value}' is not a valid integer.")

    except Exception as e:
        logging.error(f"An unexpected error occurred: {e}")
        print("An unexpected error occurred.")
    return None

file_content = read_file('nonexistent_file.txt')
if file_content:
    print(file_content)

user_input = 'abc'
number = convert_to_integer(user_input)
if number is not None:
    print(f"Converted number: {number}")

ERROR:root:FileNotFoundError: The file at nonexistent_file.txt was not found.
ERROR:root:ValueError: Unable to convert 'abc' to an integer.

Error: The file at nonexistent_file.txt was not found.
Error: 'abc' is not a valid integer.